app:
  id: content-search-service

spring:
  application:
    name: content-search-service

apollo:
  bootstrap:
    enabled: true
    namespaces: application,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-cloud-feign,micro_service.spring-ribbon,micro_service.spring-boot-es,micro_service.swagger

#logging:
#  config: classpath:log4j2-dev.xml


